# ===============================
# CONFIGURAZIONE PRINCIPALE DEL SITO
# ===============================
site_name: "Francesco Mignogna - MDEF & Fab Lab Barcelona"
site_description: "Master in Design for Emergent Futures"
site_author: "Francesco Mignogna"
copyright: "© 2026 Francesco Mignogna"

repo_name: "mig-sketch / lavezzi-mdef"
site_url: "https://mig-sketch.github.io/lavezzi-mdef/"
repo_url: "https://github.com/mig-sketch/lavezzi-mdef"

# ===============================
# NAVIGAZIONE
# ===============================
nav:
  - Home: index.md
  - Design Studio: Design Studio.md
 

  - Term 1:
      - Fundamental for Future Makers: term1/Fundamental for Future Makers.md
      - Living with your own ideas: term1/Reflections 1 - Living with your own ideas.md
      - Unpacking tech systems & the machine paradox: term1/unpacking tech systems & the machine paradox.md
      - Atlas of Weak Signal: term1/Atlas of Weak Signal.md

  - Term 2:
      - Extended Intelligences II: term2/Extended Intelligences.md
      - Cognitive Orgies: term2/Cognitive Orgies.md
      - Narratives: term2/Narratives.md
      - Situated Design Practices: term2/Situated Design Practices.md
      - Cognitive Orgies II: term2/Cognitive Orgies II.md
      - Extended Intelligences III: term2/Extended Inteligences III.md
      - Other Species II: term2/Other SpeciesII.md

  - Term 3:
      - Cognitive Orgies III: term3/Cognitive Orgies III.md
      - Fabricating MDEFEST: term3/Fabricating MDEFEST.md

# ===============================
# EXTRA
# ===============================
extra:
  homepage: "https://mig-sketch.github.io/lavezzi-mdef/"

# ===============================
# TEMA
# ===============================
theme:
  name: material

  palette:
    - scheme: slate
      primary: blue-grey
      accent: lime

  font:
    text: "Be Vietnam"
    code: "Cutive Mono"

  features:
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tracking

# ===============================
# PLUGIN
# ===============================
plugins:
  - search

# ===============================
# ESTENSIONI MARKDOWN
# ===============================
markdown_extensions:
  - extra
  - md_in_html
  - attr_list

# ===============================
# CSS EXTRA
# ===============================
extra_css:
  - stylesheets/extra.css
